[phases.setup]
nixPkgs = ['...', 'dotnet-sdk_9']

[phases.build]
cmds = ['dotnet restore', 'dotnet publish -c Release -o out']

[start]
cmd = 'cd out && dotnet MinhaApi.dll --urls http://0.0.0.0:$PORT'
